// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0XGVw1FEt0ofAqh6PZqVBWZcg3UZjvYI',
    appId: '1:120729804270:web:bdb8e71f3a2509dcbc42ff',
    messagingSenderId: '120729804270',
    projectId: 'krishan-63',
    authDomain: 'krishan-63.firebaseapp.com',
    storageBucket: 'krishan-63.appspot.com',
    measurementId: 'G-WXD25F233W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKLO1E2qEBz2bht8L0dzEV3RPPRSY9Y1c',
    appId: '1:120729804270:android:7aa75e9208d1ab39bc42ff',
    messagingSenderId: '120729804270',
    projectId: 'krishan-63',
    storageBucket: 'krishan-63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDAlGpTZ4qaW8iyIGNzQWZ5t_PGExutW8',
    appId: '1:120729804270:ios:93efe0656500999ebc42ff',
    messagingSenderId: '120729804270',
    projectId: 'krishan-63',
    storageBucket: 'krishan-63.appspot.com',
    iosClientId: '120729804270-nj3a4pvncq5h7sduumvdicpugbg768uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDAlGpTZ4qaW8iyIGNzQWZ5t_PGExutW8',
    appId: '1:120729804270:ios:93efe0656500999ebc42ff',
    messagingSenderId: '120729804270',
    projectId: 'krishan-63',
    storageBucket: 'krishan-63.appspot.com',
    iosClientId: '120729804270-nj3a4pvncq5h7sduumvdicpugbg768uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishan',
  );
}
